<a href="https://colab.research.google.com/github/hopeletty/KerasIntro/blob/main/Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.11.0


In [ ]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train /255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


Build an ML model

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])
predictions = model(x_train[:1]).numpy()
predictions

array([[ 4.9413753e-01,  7.8421009e-01,  1.3259798e-03, -1.6070215e-01,
        -6.2951446e-02, -7.9086000e-01,  3.4183928e-01,  1.3987883e+00,
         2.3167956e-01,  7.4799061e-01]], dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.10304578, 0.1377232 , 0.06295132, 0.0535349 , 0.05903228,
        0.02850774, 0.08848872, 0.25463322, 0.07925856, 0.1328242 ]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

3.5575795

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Train and evaluate the model

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2958 - accuracy: 0.9138
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1419 - accuracy: 0.9584
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1068 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0892 - accuracy: 0.9724
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0741 - accuracy: 0.9765


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0711 - accuracy: 0.9780 - 601ms/epoch - 2ms/step


[0.07113578170537949, 0.9779999852180481]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1339910e-06, 6.9958754e-09, 3.8653939e-06, 3.7963610e-04,
        6.0919653e-10, 2.0567897e-07, 2.7056208e-13, 9.9953043e-01,
        1.0531833e-06, 8.3670297e-05],
       [4.9612430e-09, 5.2199273e-05, 9.9994576e-01, 1.6461273e-06,
        1.1606092e-13, 1.2279551e-07, 1.4596493e-07, 5.9844545e-14,
        1.4781797e-07, 1.7502478e-13],
       [2.1092251e-06, 9.9735332e-01, 2.6575246e-04, 2.5237056e-05,
        9.9701843e-05, 2.5776788e-05, 1.2731913e-04, 1.1282109e-03,
        9.6645590e-04, 6.2252357e-06],
       [9.9966681e-01, 2.8388271e-11, 7.0813367e-06, 6.8702640e-08,
        5.9790050e-06, 1.8754138e-06, 2.7807051e-04, 2.4760516e-06,
        6.6902275e-09, 3.7657130e-05],
       [4.6033792e-06, 1.1722394e-11, 5.0771629e-05, 9.0043621e-08,
        9.9632299e-01, 2.4842407e-07, 7.3159999e-06, 2.8909195e-05,
        7.8691170e-07, 3.5843654e-03]], dtype=float32)>